Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 110
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/AbcSize:
  Max: 17
Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
